plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.gradleup.nmcp' version '1.6.2'
    id 'com.gradleup.nmcp.aggregation' version '1.6.2'
}

group = 'com.epam.deltix.rapidhash4j'
version = findProperty('releaseVersion') ?: providers.gradleProperty('version').get()

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach { options.release = 11 }

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

apply from: 'gradle/native.gradle'
apply from: 'gradle/jmh.gradle'
apply from: 'gradle/publishing.gradle'
